export const SET_USER_CREDENTIALS = "SET_USER_CREDENTIALS";
export const POST_STATUS = "POST_STATUS";
export const FETCH_FEED = "FETCH_FEED";
export const ADD_NEXT_FEED = "ADD_NEXT_FEED";
export const ADD_POST_CONTENT = "ADD_POST_CONTENT";
