# Generated by Django 3.2.12 on 2022-03-24 11:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='avatar',
            field=models.ImageField(default=django.db.models.expressions.F('author.profile_image.avatar.url'), upload_to=''),
        ),
    ]
