# Generated by Django 3.2.12 on 2022-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_feed_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
