# Generated by Django 3.2.12 on 2022-03-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_feed_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='avatar',
        ),
    ]
