# Generated by Django 4.0.4 on 2022-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_feed_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='post'),
        ),
    ]
