# Generated by Django 4.0.4 on 2022-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_feed_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
