# Generated by Django 4.0.4 on 2022-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_alter_feed_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['author'], name='user_posts_indx'),
        ),
    ]
