# Generated by Django 4.0.4 on 2022-05-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_alter_media_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
    ]
