# Generated by Django 4.0.4 on 2022-05-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feeds', '0013_remove_feed_shared_post_feed_flagged_tags_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
