# Generated by Django 4.0.4 on 2022-06-18 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_feed_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
