# Generated by Django 3.2.12 on 2022-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='height',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='width',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
