# Generated by Django 4.0.4 on 2022-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_username_search_indx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationship',
            name='unique_relationship',
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('from_person', 'to_person'), name='unique_relationship'),
        ),
    ]
