version: "3"

volumes:
  local_db: {}

services:
  webserver:
    image: nginx:latest
    container_name: exo_local_nginx_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server:/usr/share/nginx/html
    networks:
      - exo-net

  postgres:
    restart: on-failure
    image: postgres:12
    container_name: exo_local_postgres
    env_file:
      - ./.env
    volumes:
      - local_db:/var/lib/postgresql/data
    networks:
      - exo-net

  django: &django
    restart: on-failure
    build:
      context: .
      dockerfile: ./utils/django/Dockerfile
    image: exo_django_image
    container_name: exo_local_django
    volumes:
      - .:/exo
    env_file:
      - ./.env
    command: >
      /bin/bash -c "python manage.py makemigrations
                    python manage.py migrate
                    gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b :8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - exo-net

  react:
    restart: on-failure
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: ./utils/react/Dockerfile
    image: local_exo_react
    container_name: exo_local_react
    volumes:
      - ./app/:/app
      - /app/node_modules
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"
    depends_on:
      - django
    networks:
      - exo-net

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: exo_local_redisinsight
    ports:
      - '8001:8001'
    volumes:
      - ./insights:/db
    networks:
      - exo-net

  redisModules:
    image: "redislabs/redismod"
    container_name: exo_local_redismod
    ports:
      - "6379:6379"
    volumes:
      - ./rod:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisai.so
          ONNX redisai_onnxruntime/redisai_onnxruntime.so
          TF redisai_tensorflow/redisai_tensorflow.so
          TFLITE redisai_tflite/redisai_tflite.so
          TORCH redisai_torch/redisai_torch.so
        --loadmodule /usr/lib/redis/modules/redisearch.so MINPREFIX 3
        --loadmodule /usr/lib/redis/modules/redisgraph.so
        --loadmodule /usr/lib/redis/modules/redistimeseries.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --loadmodule /usr/lib/redis/modules/redisbloom.so
        --loadmodule /usr/lib/redis/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so
        --save 60 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - exo-net

  celery:
    <<: *django
    image: celery-exo-image
    restart: always
    container_name: exo_local_celery
    ports: []
    command: >
      /bin/bash -c "celery -A config.celery_app worker -l DEBUG &&
             celery -A config.celery_app beat -l INFO"
    depends_on:
      - postgres
      - redisModules
    networks:
      - exo-net

  mailhog:
    image: mailhog/mailhog
    container_name: exo_local_mailhog
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Browsable view of mailhog UI
    restart: unless-stopped
    networks:
      - exo-net

networks:
  exo-net:
    driver: bridge
