# Generated by Django 4.0.4 on 2022-05-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('feeds', '0008_feed_user_posts_indx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='media',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content/')),
                ('object_id', models.PositiveIntegerField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='feeds_media_content_9846a7_idx'),
        ),
    ]
