# Generated by Django 4.0.4 on 2022-05-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_remove_feed_media_media_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='feeds_media_content_9846a7_idx',
        ),
        migrations.RemoveField(
            model_name='media',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='object_id',
        ),
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_photos', to='feeds.feed'),
        ),
    ]
