# Generated by Django 4.0.4 on 2022-05-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0014_alter_tags_content_type_alter_tags_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
