# Generated by Django 4.0.7 on 2022-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_rename_date_posted_comments_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
