# Generated by Django 4.0.7 on 2022-09-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
