# Generated by Django 4.0.7 on 2022-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_remove_feed_likes_remove_feed_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
