# Generated by Django 3.2.12 on 2022-03-24 12:07

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220324_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width'),
        ),
    ]
