# Generated by Django 3.2.12 on 2022-03-24 12:27

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='avatars/', width_field='width'),
        ),
    ]
