# Generated by Django 4.0.4 on 2022-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_relationship_unique_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
