# Generated by Django 4.0.7 on 2022-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/media/profile/default_profile.jpg', max_length=200, null=True),
        ),
    ]
