# Generated by Django 4.0.7 on 2022-10-19 11:26

from django.db import migrations, models
import djapps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=models.JSONField(default=djapps.accounts.models.jsondefault, null=True),
        ),
    ]
