# openapi: 3.0.0

# info:
#   title: Exo Open API Documentation Spec
#   version: 1.0.0

# servers:
#   - url: http://127.0.0.1:8000/
#     description: The Development Server

#   - url: http://exo.com/
#     description: The production server

# security:
#   - TokenAuth: []


# paths:
#   /accounts/api/v1/users:

