# for more information check out the documentation here:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Testing and Linting workflows

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1


on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8

    defaults:
      run:
        shell: bash

    services:
      postgres:
        image: docker://postgres:12

      redis:
        image: docker://redislabs/redismod
        ports:
          - 6379/tcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: develop a container for it
        uses: docker://prime2014/elope_django


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create a .env file
        run: |
          if [ ! -f .env ]; then touch ./.env; fi

      - name: Lint with flake8
        run: |
          docker-compose -f staging.yml run --rm django flake8 --statistics

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: docker://postgres:12

      redis:
        image: docker://redislabs/redismod
        ports:
          - 6379/tcp

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: develop a container for it
        uses: docker://prime2014/elope_django

      - name: Create a .env file
        run: |
          if [ ! -f .env ]; then touch ./.env; fi

      - name: Install pytest
        run: |
          pip install pytest

      - name: Test Code with pytest

        run: |
          docker-compose -f staging.yml run --rm django pytest
