# for more information check out the documentation here:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Testing and Linting workflows

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  SECRET_KEY: u6t(n6nx(+172pn#jf92-n_69vw6t8w=4e!brt_g&zxkm+-5kl
  DJANGO_SETTINGS_MODULE: config.settings.base
  POSTGRES_URL: postgres://prime:belindat2014@postgres:5432/exodb
  POSTGRES_HOST: postgres
  POSTGRES_USER: prime
  POSTGRES_PASSWORD: belindat2014
  POSTGRES_DB: exodb
  POSTGRES_PORT: 5432
  REDIS_URL: redis://redisModules:6379/0
  DEFAULT_FROM_EMAIL: Exo<exo@mail.com>


on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 --statistics

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pytest
        run: |
          pip install pytest

      - name: Test Code with pytest
        run: |
          docker-compose -f local.yml run --rm django pytest
